apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: sample-api
  namespace: applications
  labels:
    app: sample-api
spec:
  selector:
    matchLabels:
      app: sample-api
  namespaceSelector:
    matchNames:
      - applications
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
