apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-temporal-internal
  namespace: temporal
spec:
  podSelector: {}
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              name: temporal
      ports:
        - port: 7233
          protocol: TCP
        - port: 7234
          protocol: TCP
        - port: 7235
          protocol: TCP
        - port: 7239
          protocol: TCP
        - port: 5432
          protocol: TCP
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-temporal-metrics-scrape
  namespace: temporal
spec:
  podSelector: {}
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              name: observability
          podSelector:
            matchLabels:
              app: prometheus
      ports:
        - port: 9090
          protocol: TCP
